version: "3"

services:
  go:
    container_name: poker-client
    build:
      context: .
      dockerfile: go.Dockerfile
    tty: true
    volumes:
      - ./src:/go/src
    networks:
      poker:
        ipv4_address: 172.26.0.2

networks:
  poker:
    external: true
