version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./go.Dockerfile
    tty: true
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./src:/go/src
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
