version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/go/go.Dockerfile
    tty: true
    environment:
      TZ: ${TZ}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ./src:/go/src
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/mysql.Dockerfile
    volumes:
      - ./docker/mysql/dbinit:/docker-entrypoint-initdb.d
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
