version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./go.Dockerfile
    tty: true
    environment:
      TZ: ${TZ}
      DB_URL: ${DB_URL}
    volumes:
      - ./src:/go/src
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
    depends_on:
      - postgres
    networks:
      poker:
        ipv4_address: 172.26.0.3

  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      poker:
        ipv4_address: 172.26.0.4

networks:
  poker:
    external: true
