up:
	docker compose up -d --build

down:
	docker compose down

start:
	docker compose start

stop:
	docker compose stop

web:
	docker compose exec web /bin/sh

db:
	docker compose exec postgres /bin/sh
